# Generated by Django 3.2.8 on 2022-05-12 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='score',
            field=models.IntegerField(default=1500),
        ),
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.URLField(max_length=256),
        ),
    ]
