# Generated by Django 3.2.8 on 2022-05-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_record_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='momentum',
            field=models.IntegerField(null=True),
        ),
    ]
