# Generated by Django 3.2.8 on 2022-05-17 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_record_momentum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='score_difference',
            new_name='win_probability',
        ),
    ]
