# Generated by Django 3.2.8 on 2022-05-17 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_rename_score_difference_record_win_probability'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Record',
        ),
    ]
