# Generated by Django 3.2.8 on 2022-05-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='win_probability',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
    ]
