# Generated by Django 3.2.8 on 2022-05-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_alter_record_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='momentum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='streak',
            field=models.IntegerField(default=0),
        ),
    ]
