# Generated by Django 3.2.8 on 2022-05-18 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_auto_20220517_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='score_change',
            field=models.IntegerField(null=True),
        ),
    ]
