# Generated by Django 3.2.8 on 2022-05-19 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_record_score_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='rank',
            field=models.IntegerField(default=1500),
        ),
    ]
